server:
  port: 9000
spring:
  application:
    name: jdrucker-spring-boot-sample
  datasource:
    url: jdbc:sqlite:sample.db
    username: root
    password: root
    driver-class-name: org.sqlite.JDBC
  profiles:
    active: development